# Generated by Django 4.0.1 on 2023-01-03 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudsound', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='image',
            field=models.FileField(default='./media/default-cover-art_tVe9r28.png', upload_to='./media/'),
        ),
        migrations.AlterField(
            model_name='song',
            name='image',
            field=models.FileField(default='./media/default-cover-art_tVe9r28.png', upload_to='./media/'),
        ),
    ]
