# Generated by Django 4.1.4 on 2022-12-22 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cloudsound', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='songs_uploaded',
        ),
        migrations.AddField(
            model_name='song',
            name='uploader',
            field=models.ForeignKey(default='User0', on_delete=django.db.models.deletion.CASCADE, related_name='songUploader', to='cloudsound.user'),
        ),
    ]
