# Generated by Django 4.1.4 on 2022-12-22 16:33

import cloudsound.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cloudsound', '0002_remove_user_songs_uploaded_song_uploader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='uploader',
            field=models.ForeignKey(default=cloudsound.models.generateUUID, on_delete=django.db.models.deletion.CASCADE, related_name='songUploader', to='cloudsound.user'),
        ),
    ]
