# Generated by Django 4.1.4 on 2022-12-26 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloudsound', '0003_alter_song_artist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='artist',
            new_name='uploader',
        ),
    ]
