# Generated by Django 4.0.1 on 2023-01-04 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudsound', '0003_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=200),
        ),
    ]
