# Generated by Django 4.1.4 on 2022-12-22 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cloudsound', '0003_alter_song_uploader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songUploader', to='cloudsound.user'),
        ),
    ]
