# Generated by Django 4.0.1 on 2023-01-05 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cloudsound', '0004_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='uploader',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='artist', to=settings.AUTH_USER_MODEL),
        ),
    ]
