# Generated by Django 4.1.4 on 2022-12-26 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudsound', '0004_rename_artist_song_uploader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='name',
            field=models.SlugField(max_length=100),
        ),
        migrations.AlterField(
            model_name='song',
            name='name',
            field=models.SlugField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.SlugField(max_length=100),
        ),
    ]
