# Generated by Django 4.1.4 on 2022-12-22 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloudsound', '0004_alter_song_uploader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='uploader',
        ),
    ]
