# Generated by Django 4.1.4 on 2022-12-22 16:52

import cloudsound.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cloudsound', '0005_remove_song_uploader'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='uploader',
            field=models.ForeignKey(default=cloudsound.models.generateUUID, on_delete=django.db.models.deletion.CASCADE, related_name='songUploader', to='cloudsound.user'),
        ),
    ]
