# Generated by Django 4.1.4 on 2022-12-28 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudsound', '0005_alter_playlist_name_alter_song_name_alter_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='image',
            field=models.FileField(default='./image/default-cover-art.png', upload_to='./image/'),
        ),
    ]
