# Generated by Django 4.0.1 on 2023-01-06 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloudsound', '0006_alter_song_uploader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='uploader',
        ),
    ]
