# Generated by Django 4.1.4 on 2022-12-22 17:34

import builtins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cloudsound', '0007_remove_song_uploader'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='uploader',
            field=models.ForeignKey(default=builtins.id, on_delete=django.db.models.deletion.CASCADE, related_name='songUploader', to='cloudsound.user'),
            preserve_default=False,
        ),
    ]
