# Generated by Django 4.0.1 on 2023-01-07 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudsound', '0007_remove_song_uploader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='audio_file',
            field=models.FileField(null=True, upload_to='./media/'),
        ),
        migrations.AlterField(
            model_name='song',
            name='image',
            field=models.FileField(default='./media/default-cover-art_tVe9r28.png', null=True, upload_to='./media/'),
        ),
        migrations.AlterField(
            model_name='song',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
