# Generated by Django 4.0.1 on 2023-01-07 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudsound', '0008_alter_song_audio_file_alter_song_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='audio_file',
            field=models.FileField(default='temp_data', upload_to='./media/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='song',
            name='image',
            field=models.FileField(default='./media/default-cover-art_tVe9r28.png', upload_to='./media/'),
        ),
        migrations.AlterField(
            model_name='song',
            name='name',
            field=models.CharField(default='temp_data', max_length=100),
            preserve_default=False,
        ),
    ]
