# Generated by Django 4.1.4 on 2022-12-29 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudsound', '0008_playlist_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='image',
            field=models.FileField(default='./media/default-cover-art.png', upload_to='./media/'),
        ),
        migrations.AlterField(
            model_name='song',
            name='image',
            field=models.FileField(default='./media/default-cover-art.png', upload_to='./media/'),
        ),
    ]
