# Generated by Django 4.0.1 on 2023-01-01 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudsound', '0009_alter_playlist_image_alter_song_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='songs',
            field=models.ManyToManyField(related_name='song_in_playlist', to='cloudsound.Song'),
        ),
    ]
