# Generated by Django 4.0.1 on 2023-01-07 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudsound', '0010_alter_song_audio_file_alter_song_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='name',
            field=models.CharField(default='no name given', max_length=100, null=True),
        ),
    ]
