# Generated by Django 4.0.1 on 2023-01-08 04:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cloudsound', '0011_alter_song_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='uploader',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='uploader', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
